apiVersion: v1
kind: Service
metadata:
  name: {{ include "advanced-optimization-ai.fullname" . }}-frontend
  labels:
    {{- include "advanced-optimization-ai.labels" . | nindent 4 }}
    component: frontend
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "advanced-optimization-ai.selectorLabels" . | nindent 4 }}
    component: frontend
